config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :logins, :only => [:new, :create, :destroy]
  resources :users do
    resources :posts, :only => [:show]
  end
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, :presence => true
  validates :user_id, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, :length => { :minimum => 8 }, :if => :password
  validates :email, :presence => true, :uniqueness => true
  before_save :downcase_fields
  has_many :posts

  def downcase_fields
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= session[:current_user_id] &&
      User.find_by(id: session[:current_user_id])
  end

  def authenticated_only
    flash[:notice] = "please sign in first"
    redirect_to new_login_path unless session[:current_user_id]
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.where(:email => params[:email].downcase).first
    if user && user.authenticate(params[:password])
      flash[:notice] = "You have been logged in"
      session[:current_user_id] = user.id
      redirect_to root_url
    else
      flash[:notice] = "There was a problem logging in, please try again"
      render :new
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    flash[:notice] = "You have been logged out"
    redirect_to root_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticated_only, only: :new

  def index
    @posts = Post.all
  end

  def new

    @post = Post.new
  end

  def create
    user = User.find(session[:current_user_id])
    @post = Post.create(post_params)
    @post.user = user
    if @post.save
      flash[:notice] = "post created"
      redirect_to user_post_path(user, @post)
    else
      flash[:notice] = "post faileddd"
      render new
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      flash[:notice] = 'welcome!'
      redirect_to root_url
    else
      flash[:notice] = 'there was a problem, please try again'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflowClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session[:current_user_id] %>
    <nav>
      <%= link_to "Home", root_url %>
      <%= link_to "Log Out", login_path(0),
                  :data => {:method => "delete"}%>
                </nav>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Login", new_login_path %>
    <% end %>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/logins/new.html.haml
= form_tag "/logins", method: "post" do
  = label_tag :email
  = text_field_tag :email
  = label_tag :password
  = password_field_tag :password
  = submit_tag "Login", :id => "signin"

app/views/posts/index.html.haml
- @posts.each do |post|
  = post.content
  = post.user_id
  %br
  .my_class{ id: "#{post.id}"}
    - x = 2
    - if x == 0
      = x
    - else
      %p x doesnt equal 0
    %p= link_to "this is a link", root_url
.footer
  %p footer text

=link_to "New Post", new_post_path

app/views/posts/new.html.haml
= form_for [@user, @post] do |f|
  = f.label :content
  = f.text_field :content
  = f.submit

app/views/users/new.html.haml
= form_for @user do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.submit